name: ar101_doppio
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.10
  - numpy==2.2.6
  - cartopy==0.25.0
  - xarray==2025.4.0
  - pandas==2.3.3
  - jupyterlab==4.5.7
  - dask==2026.3.0
  - bottleneck==1.6.0
  - netcdf4==1.7.4
  - xroms==0.6.2
